// <auto-generated />
using CourseScore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseScore.Migrations
{
    [DbContext(typeof(CourseScoreDb))]
    [Migration("20221214162859_improved the controller")]
    partial class improvedthecontroller
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseScore.Models.CourseCode", b =>
                {
                    b.Property<string>("matricNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("courseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("matricNo");

                    b.ToTable("CourseCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
